---
- name: MSG Linux Servers - Starting Deploy
  hosts: targets
  tasks:
    - name: APT | Update System
      ansible.builtin.shell: "echo 'Teste' > /tmp/teste.txt"
      become: true

- name: Update Debian Linux Servers - Starting Deploy
  hosts: targets
  tasks:
    - name: Debian Like | Update System
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: yes
      become: true
...
